# Generated by Django 2.0.4 on 2018-04-17 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='用户标识')),
                ('openid', models.CharField(max_length=128, verbose_name='微信OpenId')),
                ('session_key', models.CharField(max_length=128, verbose_name='会话密钥')),
                ('unionid', models.CharField(blank=True, max_length=128, null=True, verbose_name='统一Id')),
                ('coin', models.IntegerField(default=100, verbose_name='金币')),
                ('nick_name', models.CharField(max_length=256, null=True, verbose_name='昵称')),
                ('tou_url', models.CharField(max_length=256, null=True, verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='GroupShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=128, verbose_name='群ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='rhesis_contest.AppUser', verbose_name='群用户')),
            ],
            options={
                'verbose_name': '群分享',
                'verbose_name_plural': '群分享',
            },
        ),
        migrations.CreateModel(
            name='Rhesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynasty', models.CharField(max_length=16, verbose_name='朝代')),
                ('author', models.CharField(max_length=16, verbose_name='作者')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('first', models.CharField(max_length=128, verbose_name='上一句')),
                ('second', models.CharField(max_length=128, verbose_name='下一句')),
            ],
            options={
                'verbose_name': '名句',
                'verbose_name_plural': '名句',
            },
        ),
        migrations.CreateModel(
            name='RhesisTag',
            fields=[
                ('tag', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='标签')),
            ],
        ),
        migrations.AddField(
            model_name='rhesis',
            name='tags',
            field=models.ManyToManyField(to='rhesis_contest.RhesisTag', verbose_name='标签'),
        ),
    ]
