# Generated by Django 2.0.4 on 2018-04-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rhesistag',
            options={'verbose_name': '名句标签', 'verbose_name_plural': '名句标签'},
        ),
    ]
