# Generated by Django 2.0.4 on 2018-04-18 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0002_auto_20180417_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question', models.IntegerField(default=1, verbose_name='当前问题')),
            ],
            options={
                'verbose_name': '游戏房间',
                'verbose_name_plural': '游戏房间',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=128, verbose_name='通道名')),
                ('answer1', models.IntegerField(null=True, verbose_name='答案1')),
                ('time1', models.IntegerField(default=0, verbose_name='答题1时间')),
                ('answer2', models.IntegerField(null=True, verbose_name='答案2')),
                ('time2', models.IntegerField(default=0, verbose_name='答题2时间')),
                ('answer3', models.IntegerField(null=True, verbose_name='答案3')),
                ('time3', models.IntegerField(default=0, verbose_name='答题3时间')),
                ('answer4', models.IntegerField(null=True, verbose_name='答案4')),
                ('time4', models.IntegerField(default=0, verbose_name='答题4时间')),
                ('answer5', models.IntegerField(null=True, verbose_name='答案5')),
                ('time5', models.IntegerField(default=0, verbose_name='答题5时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后活动时间')),
            ],
            options={
                'verbose_name': '玩家',
                'verbose_name_plural': '玩家',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=128, verbose_name='题干')),
                ('dynasty', models.CharField(max_length=16, verbose_name='朝代')),
                ('author', models.CharField(max_length=16, verbose_name='作者')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('type', models.IntegerField(default=1, verbose_name='上句或下句')),
                ('option1', models.CharField(max_length=128, verbose_name='选项1')),
                ('option2', models.CharField(max_length=128, verbose_name='选项2')),
                ('option3', models.CharField(max_length=128, verbose_name='选项3')),
                ('option4', models.CharField(max_length=128, verbose_name='选项4')),
                ('answer', models.IntegerField(default=0, verbose_name='答案')),
                ('tags', models.ManyToManyField(to='rhesis_contest.RhesisTag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
        migrations.RemoveField(
            model_name='rhesis',
            name='tags',
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_mock',
            field=models.BooleanField(default=False, verbose_name='是否虚拟用户'),
        ),
        migrations.DeleteModel(
            name='Rhesis',
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhesis_contest.AppUser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1_room', to='rhesis_contest.Player', verbose_name='游戏房间'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2_room', to='rhesis_contest.Player', verbose_name='游戏房间'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='question1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q1_room', to='rhesis_contest.Question', verbose_name='问题1'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='question2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q2_room', to='rhesis_contest.Question', verbose_name='问题2'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='question3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q3_room', to='rhesis_contest.Question', verbose_name='问题3'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='question4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q4_room', to='rhesis_contest.Question', verbose_name='问题4'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='question5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q5_room', to='rhesis_contest.Question', verbose_name='问题5'),
        ),
    ]
