# Generated by Django 2.0.4 on 2018-04-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0005_auto_20180419_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.CharField(default='451c532a4d0d4391806df6f741c2abec', max_length=128, primary_key=True, serialize=False, verbose_name='用户标识'),
        ),
    ]
