# Generated by Django 2.0.4 on 2018-04-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0007_auto_20180419_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='tou_url',
            new_name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='current_question',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='for_friend',
            field=models.BooleanField(default=False, verbose_name='只为好友'),
        ),
    ]
