# Generated by Django 2.0.4 on 2018-04-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0008_auto_20180419_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupShare',
            new_name='UserShareInfo',
        ),
    ]
