# Generated by Django 2.0.4 on 2018-04-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0009_auto_20180419_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usershareinfo',
            options={'verbose_name': '用户分享', 'verbose_name_plural': '用户分享'},
        ),
        migrations.AlterField(
            model_name='usershareinfo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_info', to='rhesis_contest.AppUser', verbose_name='分享至'),
        ),
        migrations.AlterField(
            model_name='usershareinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_info', to='rhesis_contest.AppUser', verbose_name='分享者'),
        ),
    ]
