# Generated by Django 2.0.4 on 2018-04-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0011_auto_20180419_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usershareinfo',
            old_name='group',
            new_name='to_user',
        ),
    ]
