# Generated by Django 2.0.4 on 2018-04-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0012_auto_20180419_2319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usershareinfo',
            unique_together={('from_user', 'to_user')},
        ),
    ]
