# Generated by Django 2.0.4 on 2018-04-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0013_auto_20180419_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time1',
            field=models.IntegerField(null=True, verbose_name='答题1时间'),
        ),
        migrations.AlterField(
            model_name='player',
            name='time2',
            field=models.IntegerField(null=True, verbose_name='答题2时间'),
        ),
        migrations.AlterField(
            model_name='player',
            name='time3',
            field=models.IntegerField(null=True, verbose_name='答题3时间'),
        ),
        migrations.AlterField(
            model_name='player',
            name='time4',
            field=models.IntegerField(null=True, verbose_name='答题4时间'),
        ),
        migrations.AlterField(
            model_name='player',
            name='time5',
            field=models.IntegerField(null=True, verbose_name='答题5时间'),
        ),
    ]
