# Generated by Django 2.0.4 on 2018-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0015_remove_player_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='random_order',
            field=models.IntegerField(default=0, verbose_name='随机顺序'),
        ),
    ]
