# Generated by Django 2.0.4 on 2018-04-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0016_appuser_random_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(max_length=256, null=True, verbose_name='标签'),
        ),
        migrations.DeleteModel(
            name='RhesisTag',
        ),
    ]
