# Generated by Django 2.0.4 on 2018-04-26 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0017_auto_20180424_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1_room', to='rhesis_contest.Player', verbose_name='游戏房间'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2_room', to='rhesis_contest.Player', verbose_name='游戏房间'),
        ),
    ]
