# Generated by Django 2.0.4 on 2018-05-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0019_auto_20180426_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynasty', models.CharField(max_length=16, verbose_name='朝代')),
                ('author', models.CharField(max_length=16, verbose_name='作者')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('annotation', models.CharField(max_length=8192, verbose_name='注释')),
                ('full_text', models.CharField(max_length=8192, verbose_name='全文')),
                ('translation', models.CharField(max_length=8192, verbose_name='翻译')),
            ],
            options={
                'verbose_name': '玩家',
                'verbose_name_plural': '玩家',
            },
        ),
        migrations.AddField(
            model_name='gameroom',
            name='continue_play',
            field=models.IntegerField(default=0, verbose_name='是否继续游戏'),
        ),
        migrations.AddField(
            model_name='question',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhesis_contest.Poetry', verbose_name='出处'),
        ),
    ]
