# Generated by Django 2.0.4 on 2018-05-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0022_auto_20180505_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poetry',
            options={'verbose_name': '诗词', 'verbose_name_plural': '诗词'},
        ),
    ]
