# Generated by Django 2.0.4 on 2018-05-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhesis_contest', '0023_auto_20180505_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='level_score',
            field=models.IntegerField(default=0, verbose_name='当前级别分数'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='questions',
            field=models.ManyToManyField(related_name='已测验问题', to='rhesis_contest.Question'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='rhesis_contest.AppUser', verbose_name='用户'),
        ),
    ]
